import Foundation

enum GenerateGuide {
    static func content(locale: GuideLocale) -> CommandGuide {
        switch locale {
        case .en:   return en
        case .ptBR: return ptBR
        case .es:   return es
        }
    }

    // MARK: - English

    static let en = CommandGuide(
        command: "generate",
        purpose: "Generate an Xcode project (.xcodeproj) from a project.yml spec file.",
        agentSummary: "Call this command after any change to project.yml or when the .xcodeproj is missing. It is fully non-interactive and safe to run in CI or agent loops. Exits 0 on success, non-zero on spec validation or write errors.",
        whenToUse: [
            "After editing project.yml (adding targets, sources, dependencies, build settings).",
            "After cloning a repository that uses XcodeGen instead of committing the .xcodeproj.",
            "In CI pipelines before building with xcodebuild.",
            "When an LLM agent modifies project.yml and needs the .xcodeproj to reflect the change.",
        ],
        workflow: [
            "Run preGenCommand (if defined in project.yml options).",
            "Load and parse the spec file(s).",
            "Validate the spec (targets, configs, schemes, packages, dependencies).",
            "Generate Info.plist and other plist files.",
            "Generate the PBX project graph in memory.",
            "Write the .xcodeproj to disk.",
            "Write cache file (if --use-cache is set).",
            "Run postGenCommand (if defined in project.yml options).",
        ],
        parameters: [
            .init(name: "--spec", required: false, kind: "key",
                  description: "Path to the spec file. Comma-separate to merge multiple specs.",
                  defaultValue: "project.yml", example: "--spec path/to/project.yml"),
            .init(name: "--project", required: false, kind: "key",
                  description: "Directory where the .xcodeproj will be written.",
                  defaultValue: "Same directory as the spec", example: "--project ./Build"),
            .init(name: "--project-root", required: false, kind: "key",
                  description: "Root directory for resolving relative paths in the spec.",
                  defaultValue: "Directory containing the spec", example: "--project-root ../"),
            .init(name: "--use-cache", required: false, kind: "flag",
                  description: "Skip generation if the spec has not changed since the last cached run.",
                  defaultValue: "false", example: "--use-cache"),
            .init(name: "--cache-path", required: false, kind: "key",
                  description: "Custom path for the cache file.",
                  defaultValue: "~/.xcodegen/cache/{SPEC_HASH}", example: "--cache-path .xcodegen-cache"),
            .init(name: "--only-plists", required: false, kind: "flag",
                  description: "Generate only plist files; skip .xcodeproj generation.",
                  defaultValue: "false", example: "--only-plists"),
            .init(name: "--quiet", required: false, kind: "flag",
                  description: "Suppress all informational output.",
                  defaultValue: "false", example: "--quiet"),
            .init(name: "--no-env", required: false, kind: "flag",
                  description: "Disable environment variable expansion inside the spec.",
                  defaultValue: "false", example: "--no-env"),
            .init(name: "--lang", required: false, kind: "key",
                  description: "Language for --guide output. One of: en, pt-br, es.",
                  defaultValue: "Detected from LANG environment variable", example: "--lang pt-br"),
        ],
        examples: [
            .init(description: "Basic usage — generate from default project.yml",
                  command: "xcodegen generate",
                  expectedOutput: "⚙️  Generating plists...\n⚙️  Generating project...\n⚙️  Writing project...\nCreated project at /path/to/MyApp.xcodeproj"),
            .init(description: "Use cache to skip unchanged specs (ideal for CI)",
                  command: "xcodegen generate --use-cache",
                  expectedOutput: "Project MyApp has not changed since cache was written"),
            .init(description: "Custom spec path",
                  command: "xcodegen generate --spec Configuration/project.yml",
                  expectedOutput: nil),
            .init(description: "Suppress output for scripted environments",
                  command: "xcodegen generate --quiet",
                  expectedOutput: ""),
        ],
        commonErrors: [
            .init(error: "No project spec found at /path/project.yml",
                  cause: "The spec file does not exist at the expected path.",
                  fix: "Run from the directory containing project.yml, or pass --spec with the correct path."),
            .init(error: "Validation error: invalidTargetSource",
                  cause: "A source path declared in the spec does not exist on disk.",
                  fix: "Check that the path is correct relative to the project root. Use 'optional: true' for paths that may not exist."),
            .init(error: "missingUsername",
                  cause: "The USER environment variable is not set.",
                  fix: "Ensure USER is set in the environment. In Docker containers: export USER=runner."),
        ],
        relatedCommands: ["dump", "cache"]
    )

    // MARK: - Portuguese (Brazil)

    static let ptBR = CommandGuide(
        command: "generate",
        purpose: "Gerar um projeto Xcode (.xcodeproj) a partir de um arquivo de spec project.yml.",
        agentSummary: "Chame este comando após qualquer alteração no project.yml ou quando o .xcodeproj estiver ausente. É completamente não-interativo e seguro para rodar em CI ou loops de agente. Retorna 0 em sucesso, não-zero em erros de validação ou escrita.",
        whenToUse: [
            "Após editar o project.yml (adicionando targets, fontes, dependências, build settings).",
            "Após clonar um repositório que usa XcodeGen em vez de commitar o .xcodeproj.",
            "Em pipelines de CI antes de compilar com xcodebuild.",
            "Quando um agente LLM modifica o project.yml e precisa que o .xcodeproj reflita a mudança.",
        ],
        workflow: [
            "Executar preGenCommand (se definido nas opções do project.yml).",
            "Carregar e parsear o(s) arquivo(s) de spec.",
            "Validar o spec (targets, configs, schemes, packages, dependências).",
            "Gerar Info.plist e outros arquivos plist.",
            "Gerar o grafo do projeto PBX em memória.",
            "Escrever o .xcodeproj no disco.",
            "Escrever o arquivo de cache (se --use-cache estiver ativo).",
            "Executar postGenCommand (se definido nas opções do project.yml).",
        ],
        parameters: [
            .init(name: "--spec", required: false, kind: "key",
                  description: "Caminho para o arquivo de spec. Separe por vírgula para mesclar múltiplos specs.",
                  defaultValue: "project.yml", example: "--spec caminho/para/project.yml"),
            .init(name: "--project", required: false, kind: "key",
                  description: "Diretório onde o .xcodeproj será escrito.",
                  defaultValue: "Mesmo diretório do spec", example: "--project ./Build"),
            .init(name: "--project-root", required: false, kind: "key",
                  description: "Diretório raiz para resolver caminhos relativos no spec.",
                  defaultValue: "Diretório contendo o spec", example: "--project-root ../"),
            .init(name: "--use-cache", required: false, kind: "flag",
                  description: "Pula a geração se o spec não mudou desde o último run cacheado.",
                  defaultValue: "false", example: "--use-cache"),
            .init(name: "--cache-path", required: false, kind: "key",
                  description: "Caminho customizado para o arquivo de cache.",
                  defaultValue: "~/.xcodegen/cache/{SPEC_HASH}", example: "--cache-path .xcodegen-cache"),
            .init(name: "--only-plists", required: false, kind: "flag",
                  description: "Gera apenas os arquivos plist; pula a geração do .xcodeproj.",
                  defaultValue: "false", example: "--only-plists"),
            .init(name: "--quiet", required: false, kind: "flag",
                  description: "Suprime toda saída informacional.",
                  defaultValue: "false", example: "--quiet"),
            .init(name: "--no-env", required: false, kind: "flag",
                  description: "Desabilita a expansão de variáveis de ambiente dentro do spec.",
                  defaultValue: "false", example: "--no-env"),
            .init(name: "--lang", required: false, kind: "key",
                  description: "Idioma para a saída do --guide. Um de: en, pt-br, es.",
                  defaultValue: "Detectado da variável de ambiente LANG", example: "--lang pt-br"),
        ],
        examples: [
            .init(description: "Uso básico — gerar a partir do project.yml padrão",
                  command: "xcodegen generate",
                  expectedOutput: "⚙️  Generating plists...\n⚙️  Generating project...\n⚙️  Writing project...\nCreated project at /caminho/para/MeuApp.xcodeproj"),
            .init(description: "Usar cache para pular specs não alterados (ideal para CI)",
                  command: "xcodegen generate --use-cache",
                  expectedOutput: "Project MeuApp has not changed since cache was written"),
            .init(description: "Caminho de spec customizado",
                  command: "xcodegen generate --spec Configuracao/project.yml",
                  expectedOutput: nil),
        ],
        commonErrors: [
            .init(error: "No project spec found at /caminho/project.yml",
                  cause: "O arquivo de spec não existe no caminho esperado.",
                  fix: "Execute a partir do diretório que contém o project.yml, ou passe --spec com o caminho correto."),
            .init(error: "Validation error: invalidTargetSource",
                  cause: "Um caminho de fonte declarado no spec não existe no disco.",
                  fix: "Verifique se o caminho está correto relativo ao project root. Use 'optional: true' para caminhos que podem não existir."),
            .init(error: "missingUsername",
                  cause: "A variável de ambiente USER não está definida.",
                  fix: "Certifique-se de que USER está definida no ambiente. Em containers Docker: export USER=runner."),
        ],
        relatedCommands: ["dump", "cache"]
    )

    // MARK: - Spanish

    static let es = CommandGuide(
        command: "generate",
        purpose: "Generar un proyecto Xcode (.xcodeproj) a partir de un archivo de spec project.yml.",
        agentSummary: "Llame a este comando después de cualquier cambio en project.yml o cuando falte el .xcodeproj. Es completamente no interactivo y seguro para ejecutar en CI o bucles de agente. Sale con 0 en éxito, no-cero en errores de validación o escritura.",
        whenToUse: [
            "Después de editar project.yml (agregar targets, fuentes, dependencias, build settings).",
            "Después de clonar un repositorio que usa XcodeGen en lugar de commitear el .xcodeproj.",
            "En pipelines de CI antes de compilar con xcodebuild.",
            "Cuando un agente LLM modifica project.yml y necesita que el .xcodeproj refleje el cambio.",
        ],
        workflow: [
            "Ejecutar preGenCommand (si está definido en las opciones de project.yml).",
            "Cargar y parsear el/los archivo(s) de spec.",
            "Validar el spec (targets, configs, schemes, packages, dependencias).",
            "Generar Info.plist y otros archivos plist.",
            "Generar el grafo del proyecto PBX en memoria.",
            "Escribir el .xcodeproj en disco.",
            "Escribir el archivo de caché (si --use-cache está activo).",
            "Ejecutar postGenCommand (si está definido en las opciones de project.yml).",
        ],
        parameters: [
            .init(name: "--spec", required: false, kind: "key",
                  description: "Ruta al archivo de spec. Separe con coma para combinar múltiples specs.",
                  defaultValue: "project.yml", example: "--spec ruta/al/project.yml"),
            .init(name: "--project", required: false, kind: "key",
                  description: "Directorio donde se escribirá el .xcodeproj.",
                  defaultValue: "Mismo directorio que el spec", example: "--project ./Build"),
            .init(name: "--project-root", required: false, kind: "key",
                  description: "Directorio raíz para resolver rutas relativas en el spec.",
                  defaultValue: "Directorio que contiene el spec", example: "--project-root ../"),
            .init(name: "--use-cache", required: false, kind: "flag",
                  description: "Omite la generación si el spec no cambió desde la última ejecución cacheada.",
                  defaultValue: "false", example: "--use-cache"),
            .init(name: "--cache-path", required: false, kind: "key",
                  description: "Ruta personalizada para el archivo de caché.",
                  defaultValue: "~/.xcodegen/cache/{SPEC_HASH}", example: "--cache-path .xcodegen-cache"),
            .init(name: "--only-plists", required: false, kind: "flag",
                  description: "Genera solo los archivos plist; omite la generación del .xcodeproj.",
                  defaultValue: "false", example: "--only-plists"),
            .init(name: "--quiet", required: false, kind: "flag",
                  description: "Suprime toda la salida informacional.",
                  defaultValue: "false", example: "--quiet"),
            .init(name: "--no-env", required: false, kind: "flag",
                  description: "Deshabilita la expansión de variables de entorno dentro del spec.",
                  defaultValue: "false", example: "--no-env"),
            .init(name: "--lang", required: false, kind: "key",
                  description: "Idioma para la salida de --guide. Uno de: en, pt-br, es.",
                  defaultValue: "Detectado de la variable de entorno LANG", example: "--lang es"),
        ],
        examples: [
            .init(description: "Uso básico — generar desde el project.yml predeterminado",
                  command: "xcodegen generate",
                  expectedOutput: "⚙️  Generating plists...\n⚙️  Generating project...\n⚙️  Writing project...\nCreated project at /ruta/a/MiApp.xcodeproj"),
            .init(description: "Usar caché para omitir specs sin cambios (ideal para CI)",
                  command: "xcodegen generate --use-cache",
                  expectedOutput: "Project MiApp has not changed since cache was written"),
        ],
        commonErrors: [
            .init(error: "No project spec found at /ruta/project.yml",
                  cause: "El archivo de spec no existe en la ruta esperada.",
                  fix: "Ejecute desde el directorio que contiene project.yml, o pase --spec con la ruta correcta."),
            .init(error: "Validation error: invalidTargetSource",
                  cause: "Una ruta de fuente declarada en el spec no existe en disco.",
                  fix: "Verifique que la ruta es correcta relativa al project root. Use 'optional: true' para rutas que pueden no existir."),
            .init(error: "missingUsername",
                  cause: "La variable de entorno USER no está definida.",
                  fix: "Asegúrese de que USER está definida. En contenedores Docker: export USER=runner."),
        ],
        relatedCommands: ["dump", "cache"]
    )
}
